### ISSUE TITLE
How a could extract nanoseconds of now?

### ISSUE THREAD

**Issue by RaulGF92** [googleapis/nodejs-precise-date#203]
I'm trying to extract the current date in nanoseconds in my computer (node.js)

First I use your library:
```
const date = new PreciseDate();
console.log(date.toISOString()); //2022-02-04T10:54:43.806000000Z
```
That is not what I expect because micros and nanos are not fill

Then I force it with now:
```
const date = new PreciseDate(PreciseDate.now());
console.log(date.toISOString()); //2022-02-04T10:57:57.612000000Z
```
Like I didn't expect what I want I try to put it the bigInt from process util's function:
```
const nanos = process.hrtime.bigint();
const date = new PreciseDate(nanos);
console.log(date.toISOString()); //1970-01-02T01:57:08.622278515Z
```
That output is very weird...

Could you give me a solution for extracting the now with the right precision?

Best Regards!

**Comment by RaulGF92** [comment]
I was checking your doc and see the node version I'm in node version **"v12.22.1"**

Also I tried to fill the constructor with a string instead of a bigInt:

```
const nanos = process.hrtime.bigint();
const date = new PreciseDate(nanos.toString());
console.log(date.toISOString()); //1970-01-02T02:01:26.199274260Z
```

**Comment by alexander-fenster** [comment]
@RaulGF92 This module can store and return the precise nanoseconds, but it does not redefine `Date.now()` so it will only store whatever `Date.now()` returns. The only purpose of this module is to keep the precision when storing dates (better than `Date` class does), but it does not talk to the operating system in any way so cannot get the current time with high precision.

**Comment by RaulGF92** [comment]
> @RaulGF92 This module can store and return the precise nanoseconds, but it does not redefine `Date.now()` so it will only store whatever `Date.now()` returns. The only purpose of this module is to keep the precision when storing dates (better than `Date` class does), but it does not talk to the operating system in any way so cannot get the current time with high precision.

Since I wrote this, I have discovered that EnmaScript is working on a solution for that, Hopefully this will be released in future versions

https://tc39.es/proposal-temporal/docs/index.html
