### ISSUE TITLE
The 1.0 release did not make it to npm

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-precise-date#34]
Haven't had time to check the logs, but it looks like the tag and github release were created, but the `npm publish` step failed.  `npm info @google-cloud/precise-date` shows `0.1.0`.

**Comment by bcoe** [comment]
kokoro hadn't been given access to the npm token in our keystore, I fixed this a couple days ago. Package is published now:

https://www.npmjs.com/package/@google-cloud/precise-date
